name: run cypress automation

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6

      - name: setup node js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          
      - name: cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --spec cypress/e2e/1-getting-started/todo.cy.js
     
  
          



    

