name: schedular 

on:
  schedule: 
    - cron: '5 * * * *' 

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup node js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          
      - name: cypress run Advanced
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --spec cypress/e2e/Advanced

