name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      squad:
        description: 'select folder'
        required: true
        default: 'Advanced'
        type: choice
        options:
          - Advanced
          - Started

  schedule: 
    - cron: '00 09 * * FRI' 

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup node js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          
      - name: cypress run Advanced
        if: ${{ inputs.squad == 'Advanced'}}
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --spec cypress/e2e/Advanced

      - name: cypress run Started
        if: ${{ inputs.squad == 'Started'}}
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --spec cypress/e2e/Started

